name: Manual
on:
  workflow_dispatch:				# 수동 실행 이벤트
    inputs:
      greeting:					# 입력 파라미터명
        type: string				# 데이터형(문자열)
        default: Hello				# 입력 파라미터의 기본값
        required: true				# 입력 파라미터의 필수 플래그
        description: A careful word		# 입력 파라미터의 개요

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"	# 입력 파라미터의 greeting 값 출력
